# Generated by Django 6.0 on 2026-03-08 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('loan_term', models.IntegerField(help_text='Loan term in months')),
                ('ltv', models.DecimalField(decimal_places=2, help_text='Loan-to-Value percentage', max_digits=5)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Under Review', 'Under Review'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to='properties.property')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Request',
                'verbose_name_plural': 'Loan Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=255)),
                ('guarantor', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Expired', 'Expired')], default='Submitted', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('initial_funding', models.DecimalField(decimal_places=2, max_digits=15)),
                ('future_funding', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sponsor_equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_as_is_ltv', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('max_ltc', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('max_as_stabilized_ltv', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('min_as_is_dy', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('min_stabilized_dy', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('term', models.IntegerField(help_text='Term in months')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('amortization', models.CharField(max_length=255)),
                ('prepayment', models.CharField(max_length=255)),
                ('origination_fee', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('capex_reserve', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ff_and_e_reserve', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_carry_reserve', models.DecimalField(decimal_places=2, max_digits=15)),
                ('extension_conditions', models.TextField()),
                ('collateral', models.CharField(max_length=255)),
                ('recourse', models.CharField(max_length=255)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_quotes', to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='loans.loanrequest')),
            ],
            options={
                'verbose_name': 'Loan Quote',
                'verbose_name_plural': 'Loan Quotes',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
