# Generated by Django 6.0 on 2026-03-03 23:04

import django.db.models.deletion
import memorandums.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorandum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Generating', 'Generating'), ('Draft', 'Draft'), ('Failed', 'Failed'), ('Published', 'Published')], default='Generating', max_length=20)),
                ('mode', models.CharField(choices=[('Editor', 'Editor'), ('Preview', 'Preview')], default='Editor', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandums', to='properties.property')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memorandum',
                'verbose_name_plural': 'Memorandums',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemorandumSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('property_information', 'Property Information'), ('executive_summary', 'Executive Summary'), ('property_overview', 'Property Overview'), ('property_highlights', 'Property Highlights'), ('area_overview', 'Area Overview'), ('area_highlights', 'Area Highlights'), ('market_summary', 'Market Summary'), ('financing_summary', 'Financing Summary'), ('financial_analysis', 'Financial Analysis'), ('sales_comparables', 'Sales Comparables'), ('lease_comparables', 'Lease Comparables'), ('area_amenities', 'Area Amenities'), ('sponsorship', 'Sponsorship'), ('disclaimer', 'Disclaimer')], max_length=50)),
                ('content', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to=memorandums.models.section_image_upload_path)),
                ('order', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memorandum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='memorandums.memorandum')),
            ],
            options={
                'verbose_name': 'Memorandum Section',
                'verbose_name_plural': 'Memorandum Sections',
                'ordering': ['order'],
                'unique_together': {('memorandum', 'section_type')},
            },
        ),
    ]
