# Generated by Django 6.0 on 2026-03-11 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MEMORANDUM_GENERATED', 'Memorandum Generated'), ('LOAN_REQUEST_CREATED', 'Loan Request Created'), ('LOAN_REQUEST_UPDATED', 'Loan Request Updated'), ('QUOTE_SUBMITTED', 'Quote Submitted'), ('QUOTE_ACCEPTED', 'Quote Accepted'), ('QUOTE_DECLINED', 'Quote Declined'), ('MANUAL', 'Manual')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memorandum_id', models.IntegerField(blank=True, null=True)),
                ('loan_request_id', models.IntegerField(blank=True, null=True)),
                ('quote_id', models.IntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
